services:
#    pokemon.example:
#        class: PokemonBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    pokemon.admin.pokemon:
        class: PokemonBundle\Admin\PokemonAdmin
        tags:
           - {name: sonata.admin, manager_type: orm, group: "pokemon.admin.group.content", label: "pokemon.admin.model.pokemon", label_catalogue: "PokemonBundle"}
        arguments:
            - ~
            - PokemonBundle\Entity\Pokemon
            - ~
        calls:
           - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
    pokemon.admin.user:
            class: PokemonBundle\Admin\UserAdmin
            tags:
               - {name: sonata.admin, manager_type: orm, group: "pokemon.admin.group.content", label: "pokemon.admin.model.user", label_catalogue: "PokemonBundle"}
            arguments:
                - ~
                - PokemonBundle\Entity\User
                - ~
            calls:
               - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
