services:
#    pokemon.example:
#        class: PokemonBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    pokemon.admin.pokemon:
        class: PokemonBundle\Admin\PokemonAdmin
        tags:
           - {name: sonata.admin, manager_type: orm, group: "pokemon.admin.group.content", label: "pokemon.admin.model.pokemon", label_catalogue: "PokemonBundle"}
        arguments:
            - ~
            - PokemonBundle\Entity\Pokemon
            - ~
        calls:
           - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
    pokemon.admin.point:
        class: PokemonBundle\Admin\PointAdmin
        tags:
           - {name: sonata.admin, manager_type: orm, group: "pokemon.admin.group.content", label: "pokemon.admin.model.point", label_catalogue: "PokemonBundle"}
        arguments:
            - ~
            - PokemonBundle\Entity\Point
            - ~
        calls:
           - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
    pokemon.admin.user:
        class: PokemonBundle\Admin\UserAdmin
        tags:
           - {name: sonata.admin, manager_type: orm, group: "pokemon.admin.group.content", label: "pokemon.admin.model.user", label_catalogue: "PokemonBundle"}
        arguments:
           - ~
           - PokemonBundle\Entity\User
           - ~
        calls:
           - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
    pokemon.admin.email:
        class: PokemonBundle\Admin\EmailTemplateAdmin
        tags:
           - {name: sonata.admin, manager_type: orm, label: "pokemon.admin.model.email", label_catalogue: "PokemonBundle"}
        arguments:
           - ~
           - PokemonBundle\Entity\EmailTemplate
           - ~
        calls:
           - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
    pokemon.admin.blog:
        class: PokemonBundle\Admin\BlogAdmin
        tags:
           - {name: sonata.admin, manager_type: orm, label: "pokemon.admin.model.blog", label_catalogue: "PokemonBundle"}
        arguments:
           - ~
           - PokemonBundle\Entity\Blog
           - ~
        calls:
           - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]