imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@PokemonBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    translator:      { fallbacks: [en, ru] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      true
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sonata_user:
    security_acl: true
    manager_type: orm
    # class:              # Entity Classes
    #    user:           PokemonBundle\Entity\User
    #    group:          PokemonBundle\Entity\UserGroup

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: PokemonBundle\Entity\User
    group:
        group_class:   PokemonBundle\Entity\UserGroup
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
           contexts:   [admin]
        #sonata.user.block.menu:    # used to display the menu in profile pages
        #sonata.user.block.account: # used to display menu option (login option)
        #sonata.block.service.text: # used to if you plan to use Sonata user routes

sonata_admin:
    title:      POKEMON
    options:
        use_select2:    true
    security:
        handler: sonata.admin.security.handler.acl
    templates:
        layout: main_layout.html.twig
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
    dashboard:
        groups:
            pokemon.admin.pokemon:
                label: pokemon.admin
                label_catalogue: PokemonBundle
                items:
                    - pokemon.admin.pokemon
                    - pokemon.admin.point
                    - pokemon.admin.user
                    - pokemon.admin.email

sonata_translation:
    locales: [en, ru]
    default_locale: en