document_root: /Users/N1/Sites/pokemon/pokemon/web
document_root2: D:/OpenServer/domains/pokemon/pokemon/web
site: http://test1.sheepfish.pro
# 1 = 111 km
# 0.01 = 1.11 km
# 0.001 = 0.111 km
page_title: Pokémon GO
banner: /images/pok-ban.jpg
logo:
    image:        /images/logo.png
    text:         Logo
main_menu:
    main:
        title:    Главная
        link:     /
    about:
        title:    О нас
        link:     /about
    contacts:
        title:    Контакты
        link:     /contacts
copi_right: 2016 Copyright All right reserved