document_root: /Users/N1/Sites/pokemon/pokemon/web
document_root2: D:/OpenServer/domains/pokemon/pokemon/web
document_root3: /var/www/tester/data/www/test1.sheepfish.pro/web

site: http://test1.sheepfish.pro
email_from: ua456@mail.ru

fb_app_id: 1756332607957995
fb_app_secret: b5277ebb2b03b460e61c3fbd66bb612e
vk_app_id: 5575993
vk_app_secret: YKoHuxjVcKxCrOqNlpyb
gp_app_id: 977924656404-qin5hbvjr45c7k7a71eqcauplomsm0a5.apps.googleusercontent.com
gp_app_secret: w_9rXjpZX7zbm2XUjf7B7f0P
in_app_id:  f742734ffc4e4d889a2b15d1d7fb32c8
in_app_secret: 86bf148cebca49799390d6833f9f652b

# 1 = 111 km
# 0.01 = 1.11 km
# 0.001 = 0.111 km
page_title: Pokeopen
banner: /images/pok-ban.jpg
main_menu:
    main:
        title:    Главная
        link:     /
    blog:
        title:    Блог
        link:     /blog
    about:
        title:    О проекте
        link:     /about
    contacts:
        title:    Контакты
        link:     /contacts
copi_right:       2016 Copyright All right reserved