<?php

namespace PokemonBundle\Repository;

/**
 * PayCheckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayCheckRepository extends \Doctrine\ORM\EntityRepository
{
}
